#!/usr/bin/env bash
# Third-party notices for the wasm we serve (.plans/031 §2).
#
#   scripts/verify/third_party_licenses.sh              regenerate THIRD_PARTY_LICENSES.md
#   scripts/verify/third_party_licenses.sh --check      exit 1 if the file is stale
#   scripts/verify/third_party_licenses.sh --self-test  prove --check can fail
#
# One section per shipped artifact: the worker bundle (workspace graph) and the
# frontend-leptos dist (its own lockfile). Both are filtered to
# wasm32-unknown-unknown with build and dev deps dropped (about.toml).
# `--frozen` keeps it offline and deterministic; run `cargo fetch --locked` on
# both manifests first on a cold cache. The licence gate itself is
# `cargo deny check licenses` (deny.toml); this only renders the notices.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
out="$root/THIRD_PARTY_LICENSES.md"
template="$root/scripts/licenses/about.hbs"
config="$root/about.toml"

mode="write"
case "${1:-}" in
  "") ;;
  --check) mode="check" ;;
  --self-test) mode="self-test" ;;
  *) echo "usage: $0 [--check|--self-test]" >&2; exit 2 ;;
esac

command -v cargo-about >/dev/null || { echo "cargo-about not installed (brew install cargo-about)" >&2; exit 2; }

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

render() { # <label> <manifest>
  local label="$1" manifest="$2" part="$tmp/part.md"
  cargo about generate --frozen -c "$config" -m "$root/$manifest" "$template" -o "$part" 2>"$tmp/about.log" \
    || { cat "$tmp/about.log" >&2; exit 1; }
  # Blindness floor: a graph that renders empty is a broken run, not a clean one.
  grep -q '^- MIT License (' "$part" || { echo "no MIT crates rendered for $label: generator is blind" >&2; exit 2; }
  printf '## %s\n\nGraph: %s, target wasm32-unknown-unknown.\n\n' "$label" "\`$manifest\`"
  cat "$part"
}

{
  printf '# Third-party licences\n\n'
  printf 'Generated by %s (cargo-about). Do not edit by hand.\n' "\`scripts/verify/third_party_licenses.sh\`"
  printf 'Covers the crates compiled into the served wasm. First-party crates are not listed.\n\n'
  render "Worker bundle" "worker/Cargo.toml"
  printf '\n'
  render "Frontend (frontend-leptos dist)" "frontend-leptos/Cargo.toml"
} > "$tmp/new.md"

is_current() { # <file>: same bytes as a fresh render
  diff -q "$1" "$tmp/new.md" >/dev/null 2>&1
}

case "$mode" in
  self-test)
    cp "$tmp/new.md" "$tmp/same.md"
    sed 's/^- \(.*\) [0-9.]*$/- \1 0.0.0/' "$tmp/new.md" > "$tmp/bumped.md"
    head -n 20 "$tmp/new.md" > "$tmp/truncated.md"
    pass=0 fail=0
    if is_current "$tmp/same.md"; then pass=$((pass + 1)); else echo "FAIL: fresh render reads stale" >&2; fail=$((fail + 1)); fi
    for f in bumped truncated missing; do
      if is_current "$tmp/$f.md"; then echo "FAIL: $f file reads current" >&2; fail=$((fail + 1)); else pass=$((pass + 1)); fi
    done
    echo "self-test: $pass passed, $fail failed"
    [ "$fail" -eq 0 ]
    ;;
  write)
    mv "$tmp/new.md" "$out"
    echo "wrote $out ($(wc -l < "$out" | tr -d ' ') lines)"
    ;;
  check)
    if ! is_current "$out"; then
      diff -u "$out" "$tmp/new.md" | sed -n '1,40p' >&2 || true
      echo "THIRD_PARTY_LICENSES.md is stale: run scripts/verify/third_party_licenses.sh" >&2
      exit 1
    fi
    echo "THIRD_PARTY_LICENSES.md is current"
    ;;
esac
