//! Background Google Sheets sync — fire-and-forget writes via `wait_until()`.
//!
//! Each function is a standalone async task that owns all its data (no borrows
//! on the handler's stack frame). Handlers prepare the data, hand it off to
//! `ctx.wait_until()`, and return immediately.
//!
//! All functions are best-effort: errors are logged but never propagate to the
//! HTTP response. D1 is the source of truth; Sheets is a legacy mirror.

use event_checkin_domain::models::attendee::ColumnMapping;
use worker::KvStore;

use crate::http::{BatchUpdateRequest, ValueRange, batch_update_sheet};
use crate::state::AppState;

use super::{get_cached_access_token, invalidate_column_map_cache};

// ---------------------------------------------------------------------------
// Check-in
// ---------------------------------------------------------------------------

/// Write check-in columns (checked_in_at, checked_in_by, claim_token) to Sheet.
/// The timestamp is generated by the caller so the response doesn't wait for this.
#[allow(clippy::too_many_arguments)]
pub async fn mark_checked_in(
    state: AppState,
    row_index: usize,
    staff_email: String,
    claim_token: String,
    mapping: ColumnMapping,
    sheet_id: String,
    sheet_name: String,
    kv: Option<KvStore>,
    timestamp: String,
) {
    let access_token = match get_cached_access_token(&state, kv.as_ref()).await {
        Ok(t) => t,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync mark_checked_in: failed to get access token");
            return;
        }
    };

    use event_checkin_domain::models::attendee::ColumnKey as CK;

    let col_checked_in_at = mapping.column_letter(CK::CheckedInAt);
    let col_checked_in_by = mapping.column_letter(CK::CheckedInBy);
    let col_claim_token = mapping.column_letter(CK::ClaimToken);

    let data = vec![
        ValueRange {
            range: format!("{sheet_name}!{col_checked_in_at}{row_index}"),
            values: vec![vec![timestamp.clone()]],
        },
        ValueRange {
            range: format!("{sheet_name}!{col_checked_in_by}{row_index}"),
            values: vec![vec![staff_email.clone()]],
        },
        ValueRange {
            range: format!("{sheet_name}!{col_claim_token}{row_index}"),
            values: vec![vec![claim_token.clone()]],
        },
    ];

    let url =
        format!("https://sheets.googleapis.com/v4/spreadsheets/{sheet_id}/values:batchUpdate");

    let body = BatchUpdateRequest {
        data,
        value_input_option: "USER_ENTERED".to_string(),
    };

    if let Err(e) = batch_update_sheet(&url, &body, &access_token).await {
        tracing::error!(
            row_index = row_index,
            error = %e,
            "bg_sync mark_checked_in: sheet write failed"
        );
        return;
    }

    tracing::info!(
        row_index = row_index,
        staff_email = %staff_email,
        claim_token = %claim_token,
        "bg_sync: marked row as checked in"
    );

    invalidate_column_map_cache(kv.as_ref(), &sheet_id, &sheet_name).await;
}

// ---------------------------------------------------------------------------
// Virtual check-in
// ---------------------------------------------------------------------------

/// Write virtual check-in columns to Sheet.
pub async fn mark_virtual_checked_in(
    state: AppState,
    row_index: usize,
    mapping: ColumnMapping,
    sheet_id: String,
    sheet_name: String,
    kv: Option<KvStore>,
    timestamp: String,
) {
    let access_token = match get_cached_access_token(&state, kv.as_ref()).await {
        Ok(t) => t,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync mark_virtual_checked_in: failed to get access token");
            return;
        }
    };

    use event_checkin_domain::models::attendee::ColumnKey as CK;

    let col_checked_in_at = mapping.column_letter(CK::CheckedInAt);
    let col_checked_in_by = mapping.column_letter(CK::CheckedInBy);

    let data = vec![
        ValueRange {
            range: format!("{sheet_name}!{col_checked_in_at}{row_index}"),
            values: vec![vec![timestamp.clone()]],
        },
        ValueRange {
            range: format!("{sheet_name}!{col_checked_in_by}{row_index}"),
            values: vec![vec!["virtual".to_string()]],
        },
    ];

    let url =
        format!("https://sheets.googleapis.com/v4/spreadsheets/{sheet_id}/values:batchUpdate");

    let body = BatchUpdateRequest {
        data,
        value_input_option: "USER_ENTERED".to_string(),
    };

    if let Err(e) = batch_update_sheet(&url, &body, &access_token).await {
        tracing::error!(
            row_index = row_index,
            error = %e,
            "bg_sync mark_virtual_checked_in: sheet write failed"
        );
        return;
    }

    tracing::info!(
        row_index = row_index,
        "bg_sync: marked row as virtually checked in"
    );

    invalidate_column_map_cache(kv.as_ref(), &sheet_id, &sheet_name).await;
}

// ---------------------------------------------------------------------------
// Undo check-in
// ---------------------------------------------------------------------------

/// Clear check-in columns (checked_in_at, checked_in_by, claim_token, claimed_at).
pub async fn clear_checked_in(
    state: AppState,
    row_index: usize,
    staff_email: String,
    mapping: ColumnMapping,
    sheet_id: String,
    sheet_name: String,
    kv: Option<KvStore>,
) {
    let access_token = match get_cached_access_token(&state, kv.as_ref()).await {
        Ok(t) => t,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync clear_checked_in: failed to get access token");
            return;
        }
    };

    use event_checkin_domain::models::attendee::ColumnKey as CK;

    let col_checked_in_at = mapping.column_letter(CK::CheckedInAt);
    let col_checked_in_by = mapping.column_letter(CK::CheckedInBy);
    let col_claim_token = mapping.column_letter(CK::ClaimToken);
    let col_claimed_at = mapping.column_letter(CK::ClaimedAt);

    let data = vec![
        ValueRange {
            range: format!("{sheet_name}!{col_checked_in_at}{row_index}"),
            values: vec![vec![String::new()]],
        },
        ValueRange {
            range: format!("{sheet_name}!{col_checked_in_by}{row_index}"),
            values: vec![vec![String::new()]],
        },
        ValueRange {
            range: format!("{sheet_name}!{col_claim_token}{row_index}"),
            values: vec![vec![String::new()]],
        },
        ValueRange {
            range: format!("{sheet_name}!{col_claimed_at}{row_index}"),
            values: vec![vec![String::new()]],
        },
    ];

    let url =
        format!("https://sheets.googleapis.com/v4/spreadsheets/{sheet_id}/values:batchUpdate");

    let body = BatchUpdateRequest {
        data,
        value_input_option: "USER_ENTERED".to_string(),
    };

    if let Err(e) = batch_update_sheet(&url, &body, &access_token).await {
        tracing::error!(
            row_index = row_index,
            error = %e,
            "bg_sync clear_checked_in: sheet write failed"
        );
        return;
    }

    tracing::info!(
        row_index = row_index,
        staff_email = %staff_email,
        "bg_sync: cleared check-in fields (undo)"
    );

    invalidate_column_map_cache(kv.as_ref(), &sheet_id, &sheet_name).await;
}

// ---------------------------------------------------------------------------
// Claim
// ---------------------------------------------------------------------------

/// Write claim columns (solana_address, claimed_at, nft_proof_url) to Sheet.
#[allow(clippy::too_many_arguments)]
pub async fn mark_claimed(
    state: AppState,
    row_index: usize,
    wallet_address: String,
    claimed_at: String,
    nft_proof_url: String,
    mapping: ColumnMapping,
    sheet_id: String,
    sheet_name: String,
    kv: Option<KvStore>,
) {
    let access_token = match get_cached_access_token(&state, kv.as_ref()).await {
        Ok(t) => t,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync mark_claimed: failed to get access token");
            return;
        }
    };

    use event_checkin_domain::models::attendee::ColumnKey as CK;

    let col_solana = mapping.column_letter(CK::SolanaAddress);
    let col_claimed_at = mapping.column_letter(CK::ClaimedAt);
    let col_nft_proof_url = mapping.column_letter(CK::NftProofUrl);

    let data = vec![
        ValueRange {
            range: format!("{sheet_name}!{col_solana}{row_index}"),
            values: vec![vec![wallet_address.clone()]],
        },
        ValueRange {
            range: format!("{sheet_name}!{col_claimed_at}{row_index}"),
            values: vec![vec![claimed_at.clone()]],
        },
        ValueRange {
            range: format!("{sheet_name}!{col_nft_proof_url}{row_index}"),
            values: vec![vec![nft_proof_url.clone()]],
        },
    ];

    let url =
        format!("https://sheets.googleapis.com/v4/spreadsheets/{sheet_id}/values:batchUpdate");

    let body = BatchUpdateRequest {
        data,
        value_input_option: "USER_ENTERED".to_string(),
    };

    if let Err(e) = batch_update_sheet(&url, &body, &access_token).await {
        tracing::error!(
            row_index = row_index,
            error = %e,
            "bg_sync mark_claimed: sheet write failed"
        );
        return;
    }

    tracing::info!(
        row_index = row_index,
        wallet_address = %wallet_address,
        nft_proof_url = %nft_proof_url,
        "bg_sync: marked row as claimed"
    );
}

// ---------------------------------------------------------------------------
// Registration — append row
// ---------------------------------------------------------------------------

/// Append a new attendee row to Google Sheet.
#[allow(clippy::too_many_arguments)]
pub async fn append_attendee_row(
    state: AppState,
    api_id: String,
    name: String,
    first_name: String,
    last_name: String,
    email: String,
    claim_token: String,
    participation_type: String,
    registration_date: String,
    contact_channel: Option<String>,
    contact_handle: Option<String>,
    deposit_agreed: bool,
    consent_given: bool,
    photo_consent_given: bool,
    consent_marketing: Option<bool>,
    mapping: ColumnMapping,
    sheet_id: String,
    sheet_name: String,
    kv: Option<KvStore>,
) {
    let access_token = match get_cached_access_token(&state, kv.as_ref()).await {
        Ok(t) => t,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync append_attendee_row: failed to get access token");
            return;
        }
    };

    use event_checkin_domain::models::attendee::ColumnKey as CK;

    let row_len = mapping.total_columns.max(31);
    let mut row = vec![String::new(); row_len];

    let set = |row: &mut Vec<String>, key: CK, val: String| {
        let idx = mapping.get_or_default(key);
        if idx < row.len() {
            row[idx] = val;
        }
    };

    set(&mut row, CK::ApiId, api_id.clone());
    set(&mut row, CK::Name, name.clone());
    set(&mut row, CK::FirstName, first_name);
    set(&mut row, CK::LastName, last_name);
    set(&mut row, CK::Email, email.clone());
    set(&mut row, CK::TicketName, "Self-Registered".to_string());
    set(&mut row, CK::RegistrationDate, registration_date);
    set(&mut row, CK::ApprovalStatus, "Approved".to_string());
    set(&mut row, CK::ClaimToken, claim_token);
    set(&mut row, CK::ParticipationType, participation_type);
    if let Some(channel) = contact_channel {
        set(&mut row, CK::ContactChannel, channel);
    }
    if let Some(handle) = contact_handle {
        set(&mut row, CK::ContactHandle, handle);
    }
    if deposit_agreed {
        set(&mut row, CK::DepositAgreed, "Yes".to_string());
    }
    if consent_given {
        set(&mut row, CK::ConsentGiven, "Yes".to_string());
    }
    if photo_consent_given {
        set(&mut row, CK::PhotoConsent, "Yes".to_string());
    }
    if consent_marketing.unwrap_or(false) {
        set(&mut row, CK::ConsentMarketing, "Yes".to_string());
    }

    let last_col_idx = row.iter().rposition(|v| !v.is_empty()).unwrap_or(0);
    let last_col_letter = {
        let mut result = String::new();
        let mut n = last_col_idx;
        loop {
            result.insert(0, (b'A' + (n % 26) as u8) as char);
            if n < 26 {
                break;
            }
            n = (n / 26) - 1;
        }
        result
    };

    row.truncate(last_col_idx + 1);

    let url = format!(
        "https://sheets.googleapis.com/v4/spreadsheets/{sheet_id}/values/{}!A:{last_col_letter}:append?valueInputOption=USER_ENTERED&insertDataOption=INSERT_ROWS",
        urlencoding::encode(&sheet_name)
    );

    let body = crate::http::ValueRange {
        range: format!("{sheet_name}!A:{last_col_letter}"),
        values: vec![row],
    };

    if let Err(e) =
        crate::http::post_json::<serde_json::Value>(&url, &body, Some(&access_token)).await
    {
        tracing::error!(
            %api_id,
            %email,
            error = %e,
            "bg_sync append_attendee_row: sheet write failed"
        );
        return;
    }

    tracing::info!(
        %api_id,
        %email,
        "bg_sync: appended self-registration row to google sheet"
    );

    invalidate_column_map_cache(kv.as_ref(), &sheet_id, &sheet_name).await;
}

// ---------------------------------------------------------------------------
// Update operations
// ---------------------------------------------------------------------------

/// Update deposit_method column for an attendee row.
#[allow(dead_code)]
pub async fn update_deposit_method(
    state: AppState,
    sheet_id: String,
    sheet_name: String,
    kv: Option<KvStore>,
    row_index: usize,
    method: String,
    mapping: ColumnMapping,
) {
    let access_token = match get_cached_access_token(&state, kv.as_ref()).await {
        Ok(t) => t,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync update_deposit_method: failed to get access token");
            return;
        }
    };

    use event_checkin_domain::models::attendee::ColumnKey as CK;
    let col_deposit_method = mapping.column_letter(CK::DepositMethod);

    let data = vec![ValueRange {
        range: format!("{sheet_name}!{col_deposit_method}{row_index}"),
        values: vec![vec![method.clone()]],
    }];

    let url =
        format!("https://sheets.googleapis.com/v4/spreadsheets/{sheet_id}/values:batchUpdate");

    let body = BatchUpdateRequest {
        data,
        value_input_option: "USER_ENTERED".to_string(),
    };

    if let Err(e) = batch_update_sheet(&url, &body, &access_token).await {
        tracing::error!(row_index = row_index, error = %e, "bg_sync update_deposit_method: sheet write failed");
        return;
    }

    tracing::info!(row_index = row_index, method = %method, "bg_sync: updated deposit_method");
}

/// Update participation_type column.
pub async fn update_participation_type(
    state: AppState,
    row_index: usize,
    participation_type: String,
    mapping: ColumnMapping,
    sheet_id: String,
    sheet_name: String,
    kv: Option<KvStore>,
) {
    let access_token = match get_cached_access_token(&state, kv.as_ref()).await {
        Ok(t) => t,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync update_participation_type: failed to get access token");
            return;
        }
    };

    use event_checkin_domain::models::attendee::ColumnKey as CK;
    let col = mapping.column_letter(CK::ParticipationType);

    let data = vec![ValueRange {
        range: format!("{sheet_name}!{col}{row_index}"),
        values: vec![vec![participation_type.clone()]],
    }];

    let url =
        format!("https://sheets.googleapis.com/v4/spreadsheets/{sheet_id}/values:batchUpdate");

    let body = BatchUpdateRequest {
        data,
        value_input_option: "USER_ENTERED".to_string(),
    };

    if let Err(e) = batch_update_sheet(&url, &body, &access_token).await {
        tracing::error!(row_index = row_index, error = %e, "bg_sync update_participation_type: sheet write failed");
        return;
    }

    tracing::info!(row_index = row_index, %participation_type, "bg_sync: updated participation_type");
}

/// Write bank info columns.
#[allow(clippy::too_many_arguments)]
pub async fn write_bank_info(
    state: AppState,
    row_index: usize,
    bank_account: Option<String>,
    bank_name: Option<String>,
    mapping: ColumnMapping,
    sheet_id: String,
    sheet_name: String,
    kv: Option<KvStore>,
) {
    let access_token = match get_cached_access_token(&state, kv.as_ref()).await {
        Ok(t) => t,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync write_bank_info: failed to get access token");
            return;
        }
    };

    use event_checkin_domain::models::attendee::ColumnKey as CK;
    let col_bank_account = mapping.column_letter(CK::BankAccount);
    let col_bank_name = mapping.column_letter(CK::BankName);

    let mut data = vec![];
    if let Some(ref acct) = bank_account {
        data.push(ValueRange {
            range: format!("{sheet_name}!{col_bank_account}{row_index}"),
            values: vec![vec![acct.clone()]],
        });
    }
    if let Some(ref name) = bank_name {
        data.push(ValueRange {
            range: format!("{sheet_name}!{col_bank_name}{row_index}"),
            values: vec![vec![name.clone()]],
        });
    }

    if data.is_empty() {
        return;
    }

    let url =
        format!("https://sheets.googleapis.com/v4/spreadsheets/{sheet_id}/values:batchUpdate");

    let body = BatchUpdateRequest {
        data,
        value_input_option: "USER_ENTERED".to_string(),
    };

    if let Err(e) = batch_update_sheet(&url, &body, &access_token).await {
        tracing::error!(row_index = row_index, error = %e, "bg_sync write_bank_info: sheet write failed");
        return;
    }

    tracing::info!(row_index = row_index, "bg_sync: wrote bank info");
}

/// Write deposit verification columns (deposit_method, deposit_amount, deposit_verified).
#[allow(clippy::too_many_arguments)]
pub async fn write_deposit_verification(
    state: AppState,
    row_index: usize,
    deposit_method: String,
    deposit_amount: String,
    verified: bool,
    mapping: ColumnMapping,
    sheet_id: String,
    sheet_name: String,
    kv: Option<KvStore>,
) {
    let access_token = match get_cached_access_token(&state, kv.as_ref()).await {
        Ok(t) => t,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync write_deposit_verification: failed to get access token");
            return;
        }
    };

    use event_checkin_domain::models::attendee::ColumnKey as CK;
    let col_method = mapping.column_letter(CK::DepositMethod);
    let col_amount = mapping.column_letter(CK::DepositAmount);
    let col_verified = mapping.column_letter(CK::DepositVerified);

    let data = vec![
        ValueRange {
            range: format!("{sheet_name}!{col_method}{row_index}"),
            values: vec![vec![deposit_method]],
        },
        ValueRange {
            range: format!("{sheet_name}!{col_amount}{row_index}"),
            values: vec![vec![deposit_amount]],
        },
        ValueRange {
            range: format!("{sheet_name}!{col_verified}{row_index}"),
            values: vec![vec![if verified {
                "Yes".to_string()
            } else {
                "No".to_string()
            }]],
        },
    ];

    let url =
        format!("https://sheets.googleapis.com/v4/spreadsheets/{sheet_id}/values:batchUpdate");

    let body = BatchUpdateRequest {
        data,
        value_input_option: "USER_ENTERED".to_string(),
    };

    if let Err(e) = batch_update_sheet(&url, &body, &access_token).await {
        tracing::error!(row_index = row_index, error = %e, "bg_sync write_deposit_verification: sheet write failed");
        return;
    }

    tracing::info!(row_index = row_index, "bg_sync: wrote deposit verification");
}

/// Update QR code URLs for attendee rows.
pub async fn update_qr_urls(
    state: AppState,
    updates: Vec<(usize, String)>,
    mapping: ColumnMapping,
    sheet_id: String,
    sheet_name: String,
    kv: Option<KvStore>,
) {
    if updates.is_empty() {
        return;
    }

    let access_token = match get_cached_access_token(&state, kv.as_ref()).await {
        Ok(t) => t,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync update_qr_urls: failed to get access token");
            return;
        }
    };

    use event_checkin_domain::models::attendee::ColumnKey as CK;
    let col_qr = mapping.column_letter(CK::QrCodeUrl);

    let data: Vec<ValueRange> = updates
        .into_iter()
        .map(|(row_index, url)| ValueRange {
            range: format!("{sheet_name}!{col_qr}{row_index}"),
            values: vec![vec![url]],
        })
        .collect();

    let url =
        format!("https://sheets.googleapis.com/v4/spreadsheets/{sheet_id}/values:batchUpdate");

    let body = BatchUpdateRequest {
        data,
        value_input_option: "USER_ENTERED".to_string(),
    };

    if let Err(e) = batch_update_sheet(&url, &body, &access_token).await {
        tracing::error!(error = %e, "bg_sync update_qr_urls: sheet write failed");
        return;
    }

    tracing::info!(count = body.data.len(), "bg_sync: updated QR URLs");
}

/// Write refund status columns.
pub async fn write_refund_status(
    state: AppState,
    sheet_id: String,
    sheet_name: String,
    kv: Option<KvStore>,
    row_index: usize,
    refund_status: String,
    mapping: ColumnMapping,
) {
    let access_token = match get_cached_access_token(&state, kv.as_ref()).await {
        Ok(t) => t,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync write_refund_status: failed to get access token");
            return;
        }
    };

    use event_checkin_domain::models::attendee::ColumnKey as CK;
    let col_refund_status = mapping.column_letter(CK::RefundStatus);

    let data = vec![ValueRange {
        range: format!("{sheet_name}!{col_refund_status}{row_index}"),
        values: vec![vec![refund_status]],
    }];

    let url =
        format!("https://sheets.googleapis.com/v4/spreadsheets/{sheet_id}/values:batchUpdate");

    let body = BatchUpdateRequest {
        data,
        value_input_option: "USER_ENTERED".to_string(),
    };

    if let Err(e) = batch_update_sheet(&url, &body, &access_token).await {
        tracing::error!(row_index = row_index, error = %e, "bg_sync write_refund_status: sheet write failed");
        return;
    }

    tracing::info!(row_index = row_index, "bg_sync: wrote refund_status");
}

/// Write refund link column.
pub async fn write_refund_link(
    state: AppState,
    sheet_id: String,
    sheet_name: String,
    kv: Option<KvStore>,
    row_index: usize,
    refund_link: String,
    mapping: ColumnMapping,
) {
    let access_token = match get_cached_access_token(&state, kv.as_ref()).await {
        Ok(t) => t,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync write_refund_link: failed to get access token");
            return;
        }
    };

    use event_checkin_domain::models::attendee::ColumnKey as CK;
    let col_refund_link = mapping.column_letter(CK::RefundLink);

    let data = vec![ValueRange {
        range: format!("{sheet_name}!{col_refund_link}{row_index}"),
        values: vec![vec![refund_link]],
    }];

    let url =
        format!("https://sheets.googleapis.com/v4/spreadsheets/{sheet_id}/values:batchUpdate");

    let body = BatchUpdateRequest {
        data,
        value_input_option: "USER_ENTERED".to_string(),
    };

    if let Err(e) = batch_update_sheet(&url, &body, &access_token).await {
        tracing::error!(row_index = row_index, error = %e, "bg_sync write_refund_link: sheet write failed");
        return;
    }

    tracing::info!(row_index = row_index, "bg_sync: wrote refund_link");
}

/// Delete a row from the Sheet.
pub async fn delete_sheet_row(
    state: AppState,
    row_index: usize,
    _mapping: ColumnMapping,
    sheet_id: String,
    sheet_name: String,
    kv: Option<KvStore>,
) {
    let access_token = match get_cached_access_token(&state, kv.as_ref()).await {
        Ok(t) => t,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync delete_sheet_row: failed to get access token");
            return;
        }
    };

    let gid = resolve_sheet_gid(&sheet_name);

    let url = format!("https://sheets.googleapis.com/v4/spreadsheets/{sheet_id}:batchUpdate");

    // Row indices in the Sheets API are 0-based, but our row_index is 1-based (human-readable).
    // Subtract 1 for the API call.
    let api_row = row_index.saturating_sub(1);

    let body = serde_json::json!({
        "requests": [{
            "deleteDimension": {
                "range": {
                    "sheetId": gid,
                    "dimension": "ROWS",
                    "startIndex": api_row,
                    "endIndex": api_row + 1
                }
            }
        }]
    });

    if let Err(e) =
        crate::http::post_json::<serde_json::Value>(&url, &body, Some(&access_token)).await
    {
        tracing::error!(row_index = row_index, error = %e, "bg_sync delete_sheet_row: sheet write failed");
        return;
    }

    tracing::info!(row_index = row_index, "bg_sync: deleted sheet row");
    invalidate_column_map_cache(kv.as_ref(), &sheet_id, &sheet_name).await;
}

// ---------------------------------------------------------------------------
// Helper: resolve sheet GID (simple mapping, matches write.rs)
// ---------------------------------------------------------------------------

fn resolve_sheet_gid(sheet_name: &str) -> i64 {
    match sheet_name.to_lowercase().as_str() {
        "attendees" => 0,
        "staff" => 1,
        _ => 0,
    }
}
