//! Background Google Sheets sync — fire-and-forget writes via `wait_until()`.
//!
//! Each function is a standalone async task that owns all its data (no borrows
//! on the handler's stack frame). Handlers prepare the data, hand it off to
//! `ctx.wait_until()`, and return immediately.
//!
//! All functions are best-effort: errors are logged but never propagate to the
//! HTTP response. D1 is the source of truth; Sheets is a legacy mirror.

use super::a1;
use event_checkin_domain::models::attendee::{ColumnMapping, TICKET_NAME_SELF_REGISTERED};
use worker::KvStore;

use crate::http::{BatchUpdateRequest, ValueRange, batch_update_sheet};
use crate::state::AppState;

use super::locate::{resolve_row, resolve_rows};
use super::{get_cached_access_token, invalidate_column_map_cache};
use event_checkin_domain::models::attendee::SheetRow;

// ---------------------------------------------------------------------------
// Check-in
// ---------------------------------------------------------------------------

/// Write check-in columns (checked_in_at, checked_in_by, claim_token) to Sheet.
/// The timestamp is generated by the caller so the response doesn't wait for this.
#[allow(clippy::too_many_arguments)]
pub async fn mark_checked_in(
    state: AppState,
    row: SheetRow,
    staff_email: String,
    claim_token: String,
    mapping: ColumnMapping,
    sheet_id: String,
    sheet_name: String,
    kv: Option<KvStore>,
    timestamp: String,
) {
    let sheet_ref = a1::sheet_ref(&sheet_name);
    let access_token = match get_cached_access_token(&state, kv.as_ref()).await {
        Ok(t) => t,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync mark_checked_in: failed to get access token");
            return;
        }
    };
    let row_index = match resolve_row(&row, &sheet_id, &sheet_ref, &access_token).await {
        Ok(n) => n,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync mark_checked_in: row lookup failed, write skipped");
            return;
        }
    };

    use event_checkin_domain::models::attendee::ColumnKey as CK;

    let data: Vec<ValueRange> = [
        a1::cell(
            &sheet_ref,
            &mapping,
            CK::CheckedInAt,
            row_index,
            timestamp.clone(),
        ),
        a1::cell(
            &sheet_ref,
            &mapping,
            CK::CheckedInBy,
            row_index,
            staff_email.clone(),
        ),
        a1::cell(
            &sheet_ref,
            &mapping,
            CK::ClaimToken,
            row_index,
            claim_token.clone(),
        ),
    ]
    .into_iter()
    .flatten()
    .collect();

    let url =
        format!("https://sheets.googleapis.com/v4/spreadsheets/{sheet_id}/values:batchUpdate");

    let body = BatchUpdateRequest {
        data,
        value_input_option: "USER_ENTERED".to_string(),
    };

    if let Err(e) = batch_update_sheet(&url, &body, &access_token).await {
        tracing::error!(
            row_index = row_index,
            error = %e,
            "bg_sync mark_checked_in: sheet write failed"
        );
        return;
    }

    tracing::info!(
        row_index = row_index,
        staff_fingerprint = %state.log_fingerprint(&staff_email),
        claim_token_fingerprint = %crate::crypto::claim_token_fingerprint(&claim_token),
        "bg_sync: marked row as checked in"
    );

    invalidate_column_map_cache(kv.as_ref(), &sheet_id, &sheet_name).await;
}

// ---------------------------------------------------------------------------
// Virtual check-in
// ---------------------------------------------------------------------------

/// Write virtual check-in columns to Sheet.
pub async fn mark_virtual_checked_in(
    state: AppState,
    row: SheetRow,
    mapping: ColumnMapping,
    sheet_id: String,
    sheet_name: String,
    kv: Option<KvStore>,
    timestamp: String,
) {
    let sheet_ref = a1::sheet_ref(&sheet_name);
    let access_token = match get_cached_access_token(&state, kv.as_ref()).await {
        Ok(t) => t,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync mark_virtual_checked_in: failed to get access token");
            return;
        }
    };
    let row_index = match resolve_row(&row, &sheet_id, &sheet_ref, &access_token).await {
        Ok(n) => n,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync mark_virtual_checked_in: row lookup failed, write skipped");
            return;
        }
    };

    use event_checkin_domain::models::attendee::ColumnKey as CK;

    let data: Vec<ValueRange> = [
        a1::cell(
            &sheet_ref,
            &mapping,
            CK::CheckedInAt,
            row_index,
            timestamp.clone(),
        ),
        a1::cell(
            &sheet_ref,
            &mapping,
            CK::CheckedInBy,
            row_index,
            "virtual".to_string(),
        ),
    ]
    .into_iter()
    .flatten()
    .collect();

    let url =
        format!("https://sheets.googleapis.com/v4/spreadsheets/{sheet_id}/values:batchUpdate");

    let body = BatchUpdateRequest {
        data,
        value_input_option: "USER_ENTERED".to_string(),
    };

    if let Err(e) = batch_update_sheet(&url, &body, &access_token).await {
        tracing::error!(
            row_index = row_index,
            error = %e,
            "bg_sync mark_virtual_checked_in: sheet write failed"
        );
        return;
    }

    tracing::info!(
        row_index = row_index,
        "bg_sync: marked row as virtually checked in"
    );

    invalidate_column_map_cache(kv.as_ref(), &sheet_id, &sheet_name).await;
}

// ---------------------------------------------------------------------------
// Undo check-in
// ---------------------------------------------------------------------------

/// Clear check-in columns (checked_in_at, checked_in_by, claim_token, claimed_at).
pub async fn clear_checked_in(
    state: AppState,
    row: SheetRow,
    staff_email: String,
    mapping: ColumnMapping,
    sheet_id: String,
    sheet_name: String,
    kv: Option<KvStore>,
) {
    let sheet_ref = a1::sheet_ref(&sheet_name);
    let access_token = match get_cached_access_token(&state, kv.as_ref()).await {
        Ok(t) => t,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync clear_checked_in: failed to get access token");
            return;
        }
    };
    let row_index = match resolve_row(&row, &sheet_id, &sheet_ref, &access_token).await {
        Ok(n) => n,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync clear_checked_in: row lookup failed, write skipped");
            return;
        }
    };

    use event_checkin_domain::models::attendee::ColumnKey as CK;

    let data: Vec<ValueRange> = [
        a1::cell(
            &sheet_ref,
            &mapping,
            CK::CheckedInAt,
            row_index,
            String::new(),
        ),
        a1::cell(
            &sheet_ref,
            &mapping,
            CK::CheckedInBy,
            row_index,
            String::new(),
        ),
        a1::cell(
            &sheet_ref,
            &mapping,
            CK::ClaimToken,
            row_index,
            String::new(),
        ),
        a1::cell(
            &sheet_ref,
            &mapping,
            CK::ClaimedAt,
            row_index,
            String::new(),
        ),
    ]
    .into_iter()
    .flatten()
    .collect();

    let url =
        format!("https://sheets.googleapis.com/v4/spreadsheets/{sheet_id}/values:batchUpdate");

    let body = BatchUpdateRequest {
        data,
        value_input_option: "USER_ENTERED".to_string(),
    };

    if let Err(e) = batch_update_sheet(&url, &body, &access_token).await {
        tracing::error!(
            row_index = row_index,
            error = %e,
            "bg_sync clear_checked_in: sheet write failed"
        );
        return;
    }

    tracing::info!(
        row_index = row_index,
        staff_fingerprint = %state.log_fingerprint(&staff_email),
        "bg_sync: cleared check-in fields (undo)"
    );

    invalidate_column_map_cache(kv.as_ref(), &sheet_id, &sheet_name).await;
}

// ---------------------------------------------------------------------------
// Claim
// ---------------------------------------------------------------------------

/// Write claim columns (solana_address, claimed_at, nft_proof_url) to Sheet.
#[allow(clippy::too_many_arguments)]
pub async fn mark_claimed(
    state: AppState,
    row: SheetRow,
    wallet_address: String,
    claimed_at: String,
    nft_proof_url: String,
    mapping: ColumnMapping,
    sheet_id: String,
    sheet_name: String,
    kv: Option<KvStore>,
) {
    let sheet_ref = a1::sheet_ref(&sheet_name);
    let access_token = match get_cached_access_token(&state, kv.as_ref()).await {
        Ok(t) => t,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync mark_claimed: failed to get access token");
            return;
        }
    };
    let row_index = match resolve_row(&row, &sheet_id, &sheet_ref, &access_token).await {
        Ok(n) => n,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync mark_claimed: row lookup failed, write skipped");
            return;
        }
    };

    use event_checkin_domain::models::attendee::ColumnKey as CK;

    let data: Vec<ValueRange> = [
        a1::cell(
            &sheet_ref,
            &mapping,
            CK::SolanaAddress,
            row_index,
            wallet_address.clone(),
        ),
        a1::cell(
            &sheet_ref,
            &mapping,
            CK::ClaimedAt,
            row_index,
            claimed_at.clone(),
        ),
        a1::cell(
            &sheet_ref,
            &mapping,
            CK::NftProofUrl,
            row_index,
            nft_proof_url.clone(),
        ),
    ]
    .into_iter()
    .flatten()
    .collect();

    let url =
        format!("https://sheets.googleapis.com/v4/spreadsheets/{sheet_id}/values:batchUpdate");

    let body = BatchUpdateRequest {
        data,
        value_input_option: "USER_ENTERED".to_string(),
    };

    if let Err(e) = batch_update_sheet(&url, &body, &access_token).await {
        tracing::error!(
            row_index = row_index,
            error = %e,
            "bg_sync mark_claimed: sheet write failed"
        );
        return;
    }

    tracing::info!(
        row_index = row_index,
        wallet_fingerprint = %state.log_fingerprint(&wallet_address),
        nft_proof_url = %nft_proof_url,
        "bg_sync: marked row as claimed"
    );
}

// ---------------------------------------------------------------------------
// Registration — append row
// ---------------------------------------------------------------------------

/// Append a new attendee row to Google Sheet.
#[allow(clippy::too_many_arguments)]
pub async fn append_attendee_row(
    state: AppState,
    api_id: String,
    name: String,
    first_name: String,
    last_name: String,
    email: String,
    claim_token: String,
    participation_type: String,
    registration_date: String,
    contact_channel: Option<String>,
    contact_handle: Option<String>,
    deposit_agreed: bool,
    consent_given: bool,
    photo_consent_given: bool,
    consent_marketing: Option<bool>,
    mapping: ColumnMapping,
    sheet_id: String,
    sheet_name: String,
    kv: Option<KvStore>,
) {
    let sheet_ref = a1::sheet_ref(&sheet_name);
    let access_token = match get_cached_access_token(&state, kv.as_ref()).await {
        Ok(t) => t,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync append_attendee_row: failed to get access token");
            return;
        }
    };

    use event_checkin_domain::models::attendee::ColumnKey as CK;

    let row_len = mapping.total_columns.max(31);
    let mut row = vec![String::new(); row_len];

    let set = |row: &mut Vec<String>, key: CK, val: String| mapping.put(row, key, val);

    set(&mut row, CK::ApiId, api_id.clone());
    set(&mut row, CK::Name, name.clone());
    set(&mut row, CK::FirstName, first_name);
    set(&mut row, CK::LastName, last_name);
    set(&mut row, CK::Email, email.clone());
    set(
        &mut row,
        CK::TicketName,
        TICKET_NAME_SELF_REGISTERED.to_string(),
    );
    set(&mut row, CK::RegistrationDate, registration_date);
    set(&mut row, CK::ApprovalStatus, "Approved".to_string());
    set(&mut row, CK::ClaimToken, claim_token);
    set(&mut row, CK::ParticipationType, participation_type);
    if let Some(channel) = contact_channel {
        set(&mut row, CK::ContactChannel, channel);
    }
    if let Some(handle) = contact_handle {
        set(&mut row, CK::ContactHandle, handle);
    }
    if deposit_agreed {
        set(&mut row, CK::DepositAgreed, "Yes".to_string());
    }
    if consent_given {
        set(&mut row, CK::ConsentGiven, "Yes".to_string());
    }
    if photo_consent_given {
        set(&mut row, CK::PhotoConsent, "Yes".to_string());
    }
    if consent_marketing.unwrap_or(false) {
        set(&mut row, CK::ConsentMarketing, "Yes".to_string());
    }

    // Pinned to column A: a hand-edited sheet can make `:append` land offset.
    if let Err(e) =
        crate::sheets::locate::append_row(&sheet_id, &sheet_ref, row, &access_token).await
    {
        tracing::error!(
            %api_id,
            attendee_fingerprint = %state.log_fingerprint(&email),
            error = %e,
            "bg_sync append_attendee_row: sheet write failed"
        );
        return;
    }

    tracing::info!(
        %api_id,
        attendee_fingerprint = %state.log_fingerprint(&email),
        "bg_sync: appended self-registration row to google sheet"
    );

    invalidate_column_map_cache(kv.as_ref(), &sheet_id, &sheet_name).await;
}

// ---------------------------------------------------------------------------
// Update operations
// ---------------------------------------------------------------------------

/// Update deposit_method column for an attendee row.
#[allow(dead_code)]
pub async fn update_deposit_method(
    state: AppState,
    sheet_id: String,
    sheet_name: String,
    kv: Option<KvStore>,
    row: SheetRow,
    method: String,
    mapping: ColumnMapping,
) {
    let sheet_ref = a1::sheet_ref(&sheet_name);
    let access_token = match get_cached_access_token(&state, kv.as_ref()).await {
        Ok(t) => t,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync update_deposit_method: failed to get access token");
            return;
        }
    };
    let row_index = match resolve_row(&row, &sheet_id, &sheet_ref, &access_token).await {
        Ok(n) => n,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync update_deposit_method: row lookup failed, write skipped");
            return;
        }
    };

    use event_checkin_domain::models::attendee::ColumnKey as CK;

    let data: Vec<ValueRange> = [a1::cell(
        &sheet_ref,
        &mapping,
        CK::DepositMethod,
        row_index,
        method.clone(),
    )]
    .into_iter()
    .flatten()
    .collect();

    let url =
        format!("https://sheets.googleapis.com/v4/spreadsheets/{sheet_id}/values:batchUpdate");

    let body = BatchUpdateRequest {
        data,
        value_input_option: "USER_ENTERED".to_string(),
    };

    if let Err(e) = batch_update_sheet(&url, &body, &access_token).await {
        tracing::error!(row_index = row_index, error = %e, "bg_sync update_deposit_method: sheet write failed");
        return;
    }

    tracing::info!(row_index = row_index, method = %method, "bg_sync: updated deposit_method");
}

/// Update participation_type column.
pub async fn update_participation_type(
    state: AppState,
    row: SheetRow,
    participation_type: String,
    mapping: ColumnMapping,
    sheet_id: String,
    sheet_name: String,
    kv: Option<KvStore>,
) {
    let sheet_ref = a1::sheet_ref(&sheet_name);
    let access_token = match get_cached_access_token(&state, kv.as_ref()).await {
        Ok(t) => t,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync update_participation_type: failed to get access token");
            return;
        }
    };
    let row_index = match resolve_row(&row, &sheet_id, &sheet_ref, &access_token).await {
        Ok(n) => n,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync update_participation_type: row lookup failed, write skipped");
            return;
        }
    };

    use event_checkin_domain::models::attendee::ColumnKey as CK;

    let data: Vec<ValueRange> = [a1::cell(
        &sheet_ref,
        &mapping,
        CK::ParticipationType,
        row_index,
        participation_type.clone(),
    )]
    .into_iter()
    .flatten()
    .collect();

    let url =
        format!("https://sheets.googleapis.com/v4/spreadsheets/{sheet_id}/values:batchUpdate");

    let body = BatchUpdateRequest {
        data,
        value_input_option: "USER_ENTERED".to_string(),
    };

    if let Err(e) = batch_update_sheet(&url, &body, &access_token).await {
        tracing::error!(row_index = row_index, error = %e, "bg_sync update_participation_type: sheet write failed");
        return;
    }

    tracing::info!(row_index = row_index, %participation_type, "bg_sync: updated participation_type");
}

/// Write bank info columns.
#[allow(clippy::too_many_arguments)]
pub async fn write_bank_info(
    state: AppState,
    row: SheetRow,
    bank_account: Option<String>,
    bank_name: Option<String>,
    mapping: ColumnMapping,
    sheet_id: String,
    sheet_name: String,
    kv: Option<KvStore>,
) {
    let sheet_ref = a1::sheet_ref(&sheet_name);
    let access_token = match get_cached_access_token(&state, kv.as_ref()).await {
        Ok(t) => t,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync write_bank_info: failed to get access token");
            return;
        }
    };
    let row_index = match resolve_row(&row, &sheet_id, &sheet_ref, &access_token).await {
        Ok(n) => n,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync write_bank_info: row lookup failed, write skipped");
            return;
        }
    };

    use event_checkin_domain::models::attendee::ColumnKey as CK;

    let mut data = vec![];
    if let Some(ref acct) = bank_account {
        data.extend(a1::cell(
            &sheet_ref,
            &mapping,
            CK::BankAccount,
            row_index,
            acct.clone(),
        ));
    }
    if let Some(ref name) = bank_name {
        data.extend(a1::cell(
            &sheet_ref,
            &mapping,
            CK::BankName,
            row_index,
            name.clone(),
        ));
    }

    if data.is_empty() {
        return;
    }

    let url =
        format!("https://sheets.googleapis.com/v4/spreadsheets/{sheet_id}/values:batchUpdate");

    let body = BatchUpdateRequest {
        data,
        value_input_option: "USER_ENTERED".to_string(),
    };

    if let Err(e) = batch_update_sheet(&url, &body, &access_token).await {
        tracing::error!(row_index = row_index, error = %e, "bg_sync write_bank_info: sheet write failed");
        return;
    }

    tracing::info!(row_index = row_index, "bg_sync: wrote bank info");
}

/// Write deposit verification columns (deposit_method, deposit_amount, deposit_verified).
#[allow(clippy::too_many_arguments)]
pub async fn write_deposit_verification(
    state: AppState,
    row: SheetRow,
    deposit_method: String,
    deposit_amount: String,
    verified: bool,
    mapping: ColumnMapping,
    sheet_id: String,
    sheet_name: String,
    kv: Option<KvStore>,
) {
    let sheet_ref = a1::sheet_ref(&sheet_name);
    let access_token = match get_cached_access_token(&state, kv.as_ref()).await {
        Ok(t) => t,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync write_deposit_verification: failed to get access token");
            return;
        }
    };
    let row_index = match resolve_row(&row, &sheet_id, &sheet_ref, &access_token).await {
        Ok(n) => n,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync write_deposit_verification: row lookup failed, write skipped");
            return;
        }
    };

    use event_checkin_domain::models::attendee::ColumnKey as CK;

    let data: Vec<ValueRange> = [
        a1::cell(
            &sheet_ref,
            &mapping,
            CK::DepositMethod,
            row_index,
            deposit_method,
        ),
        a1::cell(
            &sheet_ref,
            &mapping,
            CK::DepositAmount,
            row_index,
            deposit_amount,
        ),
        a1::cell(
            &sheet_ref,
            &mapping,
            CK::DepositVerified,
            row_index,
            if verified {
                "Yes".to_string()
            } else {
                "No".to_string()
            },
        ),
    ]
    .into_iter()
    .flatten()
    .collect();

    let url =
        format!("https://sheets.googleapis.com/v4/spreadsheets/{sheet_id}/values:batchUpdate");

    let body = BatchUpdateRequest {
        data,
        value_input_option: "USER_ENTERED".to_string(),
    };

    if let Err(e) = batch_update_sheet(&url, &body, &access_token).await {
        tracing::error!(row_index = row_index, error = %e, "bg_sync write_deposit_verification: sheet write failed");
        return;
    }

    tracing::info!(row_index = row_index, "bg_sync: wrote deposit verification");
}

/// Update QR code URLs for attendee rows.
pub async fn update_qr_urls(
    state: AppState,
    updates: Vec<(SheetRow, String)>,
    mapping: ColumnMapping,
    sheet_id: String,
    sheet_name: String,
    kv: Option<KvStore>,
) {
    let sheet_ref = a1::sheet_ref(&sheet_name);
    if updates.is_empty() {
        return;
    }

    let access_token = match get_cached_access_token(&state, kv.as_ref()).await {
        Ok(t) => t,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync update_qr_urls: failed to get access token");
            return;
        }
    };
    let updates = match resolve_rows(updates, &sheet_id, &sheet_ref, &access_token).await {
        Ok(found) => found,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync update_qr_urls: row lookup failed, writes skipped");
            return;
        }
    };

    use event_checkin_domain::models::attendee::ColumnKey as CK;

    let data: Vec<ValueRange> = updates
        .into_iter()
        .filter_map(|(row_index, url)| {
            a1::cell(&sheet_ref, &mapping, CK::QrCodeUrl, row_index, url)
        })
        .collect();

    let url =
        format!("https://sheets.googleapis.com/v4/spreadsheets/{sheet_id}/values:batchUpdate");

    let body = BatchUpdateRequest {
        data,
        value_input_option: "USER_ENTERED".to_string(),
    };

    if let Err(e) = batch_update_sheet(&url, &body, &access_token).await {
        tracing::error!(error = %e, "bg_sync update_qr_urls: sheet write failed");
        return;
    }

    tracing::info!(count = body.data.len(), "bg_sync: updated QR URLs");
}

/// Write refund status columns.
pub async fn write_refund_status(
    state: AppState,
    sheet_id: String,
    sheet_name: String,
    kv: Option<KvStore>,
    row: SheetRow,
    refund_status: String,
    mapping: ColumnMapping,
) {
    let sheet_ref = a1::sheet_ref(&sheet_name);
    let access_token = match get_cached_access_token(&state, kv.as_ref()).await {
        Ok(t) => t,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync write_refund_status: failed to get access token");
            return;
        }
    };
    let row_index = match resolve_row(&row, &sheet_id, &sheet_ref, &access_token).await {
        Ok(n) => n,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync write_refund_status: row lookup failed, write skipped");
            return;
        }
    };

    use event_checkin_domain::models::attendee::ColumnKey as CK;

    let data: Vec<ValueRange> = [a1::cell(
        &sheet_ref,
        &mapping,
        CK::RefundStatus,
        row_index,
        refund_status,
    )]
    .into_iter()
    .flatten()
    .collect();

    let url =
        format!("https://sheets.googleapis.com/v4/spreadsheets/{sheet_id}/values:batchUpdate");

    let body = BatchUpdateRequest {
        data,
        value_input_option: "USER_ENTERED".to_string(),
    };

    if let Err(e) = batch_update_sheet(&url, &body, &access_token).await {
        tracing::error!(row_index = row_index, error = %e, "bg_sync write_refund_status: sheet write failed");
        return;
    }

    tracing::info!(row_index = row_index, "bg_sync: wrote refund_status");
}

/// Write refund link column.
pub async fn write_refund_link(
    state: AppState,
    sheet_id: String,
    sheet_name: String,
    kv: Option<KvStore>,
    row: SheetRow,
    refund_link: String,
    mapping: ColumnMapping,
) {
    let sheet_ref = a1::sheet_ref(&sheet_name);
    let access_token = match get_cached_access_token(&state, kv.as_ref()).await {
        Ok(t) => t,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync write_refund_link: failed to get access token");
            return;
        }
    };
    let row_index = match resolve_row(&row, &sheet_id, &sheet_ref, &access_token).await {
        Ok(n) => n,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync write_refund_link: row lookup failed, write skipped");
            return;
        }
    };

    use event_checkin_domain::models::attendee::ColumnKey as CK;

    let data: Vec<ValueRange> = [a1::cell(
        &sheet_ref,
        &mapping,
        CK::RefundLink,
        row_index,
        refund_link,
    )]
    .into_iter()
    .flatten()
    .collect();

    let url =
        format!("https://sheets.googleapis.com/v4/spreadsheets/{sheet_id}/values:batchUpdate");

    let body = BatchUpdateRequest {
        data,
        value_input_option: "USER_ENTERED".to_string(),
    };

    if let Err(e) = batch_update_sheet(&url, &body, &access_token).await {
        tracing::error!(row_index = row_index, error = %e, "bg_sync write_refund_link: sheet write failed");
        return;
    }

    tracing::info!(row_index = row_index, "bg_sync: wrote refund_link");
}

/// Write refund_status and refund_link for multiple attendees in a single
/// batch update. Used by the batch THB refund to mirror D1 into the Sheet.
pub async fn write_refund_batch(
    state: AppState,
    rows: Vec<usize>,
    refund_link: String,
    mapping: ColumnMapping,
    sheet_id: String,
    sheet_name: String,
    kv: Option<KvStore>,
) {
    if rows.is_empty() {
        return;
    }

    let access_token = match get_cached_access_token(&state, kv.as_ref()).await {
        Ok(t) => t,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync write_refund_batch: failed to get access token");
            return;
        }
    };

    let url =
        format!("https://sheets.googleapis.com/v4/spreadsheets/{sheet_id}/values:batchUpdate");

    let body = BatchUpdateRequest {
        data: super::write::refund_batch_ranges(
            &sheet_name,
            &mapping,
            &rows,
            "refunded",
            &refund_link,
        ),
        value_input_option: "USER_ENTERED".to_string(),
    };

    if let Err(e) = batch_update_sheet(&url, &body, &access_token).await {
        tracing::error!(error = %e, "bg_sync write_refund_batch: sheet write failed");
        return;
    }

    tracing::info!(count = rows.len(), "bg_sync: wrote batch refund");
}

/// Delete a row from the Sheet.
pub async fn delete_sheet_row(
    state: AppState,
    row_index: usize,
    _mapping: ColumnMapping,
    sheet_id: String,
    sheet_name: String,
    kv: Option<KvStore>,
) {
    let access_token = match get_cached_access_token(&state, kv.as_ref()).await {
        Ok(t) => t,
        Err(e) => {
            tracing::error!(error = %e, "bg_sync delete_sheet_row: failed to get access token");
            return;
        }
    };

    // Resolve the REAL numeric GID for this tab. The old hardcoded map
    // ("attendees" => 0) was wrong — Google assigns arbitrary GIDs (e.g.
    // 104609663), so deleting with sheetId=0 was a silent no-op and the row
    // never disappeared from the sheet.
    let gid =
        match super::resolve_sheet_gid(&state, &sheet_id, &sheet_name, kv.as_ref(), &access_token)
            .await
        {
            Ok(g) => g,
            Err(e) => {
                tracing::error!(
                    sheet_id = %sheet_id,
                    sheet_name = %sheet_name,
                    error = %e,
                    "bg_sync delete_sheet_row: failed to resolve gid"
                );
                return;
            }
        };

    let url = format!("https://sheets.googleapis.com/v4/spreadsheets/{sheet_id}:batchUpdate");

    // Row indices in the Sheets API are 0-based, but our row_index is 1-based (human-readable).
    // Subtract 1 for the API call.
    let api_row = row_index.saturating_sub(1);

    let body = serde_json::json!({
        "requests": [{
            "deleteDimension": {
                "range": {
                    "sheetId": gid,
                    "dimension": "ROWS",
                    "startIndex": api_row,
                    "endIndex": api_row + 1
                }
            }
        }]
    });

    if let Err(e) =
        crate::http::post_json::<serde_json::Value>(&url, &body, Some(&access_token)).await
    {
        tracing::error!(row_index = row_index, error = %e, "bg_sync delete_sheet_row: sheet write failed");
        return;
    }

    tracing::info!(row_index = row_index, "bg_sync: deleted sheet row");
    invalidate_column_map_cache(kv.as_ref(), &sheet_id, &sheet_name).await;
}

// resolve_sheet_gid removed — sheet GIDs are resolved dynamically via
// super::resolve_sheet_gid() in sheets/mod.rs, which fetches the real GID
// from the spreadsheet metadata. The hardcoded map here was wrong (the
// "Attendees" tab is NOT GID 0), causing row deletes to silently no-op.
