SELECT id,
       event_id,
       email,
       name,
       ticket_name,
       approval_status,
       participation_type,
       checked_in_at,
       checked_in_by,
       claim_token,
       claimed_at,
       claim_asset_id,
       claim_signature,
       qr_url,
       contact_channel,
       contact_handle,
       deposit_status,
       deposit_amount_usdc,
       deposit_tx_hash,
       refund_tx_hash,
       refund_link,
       bank_name,
       bank_account_number,
       bank_account_name,
       sheet_row_index
FROM attendees
WHERE id = ?1 AND event_id = ?2
