//! PR Pack generator page — Plan 008 Phase 4.
//!
//! Route: `/events/:id/pr-pack` (organizer+ only, wrapped in `ProtectedRoute`).
//!
//! Renders the deterministic marketing copy generated by the backend
//! (`GET /events/{id}/pr-pack`) as a stack of copy-to-clipboard cards. The page
//! is read-only — to change the copy, edit the event config and hit
//! "Regenerate". No content is edited here (Plan 008 §3.4.2: "Edit the event
//! config, regenerate").

use leptos::prelude::*;
use leptos_meta::Title;
use leptos_router::hooks::use_params;
use leptos_router::params::Params;
use wasm_bindgen::prelude::*;

use crate::api::{self, PrPackData};
use crate::components::{self, ToastType};
use crate::icons::{Icon, IconName};

/// Route parameters for `/events/:id/pr-pack`.
#[derive(Params, PartialEq, Clone, Debug)]
struct PrPackParams {
    id: Option<String>,
}

/// Clipboard JS binding — mirrors `claim.rs`. Uses the Clipboard API with a
/// textarea fallback for older browsers. Returns true on success.
#[wasm_bindgen(module = "/js/clipboard.js")]
extern "C" {
    #[wasm_bindgen(js_name = "copyToClipboard")]
    fn copy_to_clipboard_js(text: &str) -> bool;
}

/// PR Pack generator page.
///
/// On mount, fetches `GET /events/{id}/pr-pack`. "Regenerate" re-fetches
/// (useful after editing the event config). Each field card has a copy button.
#[component]
pub fn PrPack() -> impl IntoView {
    let params = use_params::<PrPackParams>();
    let event_id: String = match params.get() {
        Ok(p) => p.id.unwrap_or_default(),
        Err(_) => String::new(),
    };

    let (data, set_data) = signal(Option::<PrPackData>::None);
    let (loading, set_loading) = signal(true);
    let (error, set_error) = signal(None::<String>);
    let (toast, set_toast) = signal(None::<components::ToastMessage>);
    let (refresh_counter, set_refresh_counter) = signal(0u32);

    let do_reload = move || {
        set_refresh_counter.update(|n| *n += 1);
    };

    // Fetch on mount + on each regenerate.
    Effect::new(move |_| {
        let _ = refresh_counter.get();
        if event_id.is_empty() {
            set_loading.set(false);
            set_error.set(Some("Missing event id in URL".to_string()));
            return;
        }
        let id = event_id.clone();
        let set_d = set_data;
        let set_l = set_loading;
        let set_e = set_error;
        set_l.set(true);
        leptos::task::spawn_local(async move {
            match api::get_pr_pack(&id).await {
                Ok(payload) => {
                    set_d.set(Some(payload));
                    set_l.set(false);
                    set_e.set(None);
                }
                Err(e) => {
                    log::error!("[pr-pack] load failed: {e}");
                    set_l.set(false);
                    set_e.set(Some(format!("{e}")));
                }
            }
        });
    });

    view! {
        <Title text="PR Pack — BeThere" />
        <components::Toast toast_signal=toast />
        <div class="container layout-col-center">
            // ── Header ───────────────────────────────────────────────────
            <div style="width:100%;display:flex;justify-content:space-between;align-items:center;margin-bottom:1rem;flex-wrap:wrap;gap:0.5rem;">
                <div>
                    <a href="/admin" class="btn btn-outline btn-sm">"← Back"</a>
                </div>
                <h1 style="margin:0;font-size:1.25rem;">
                    <Icon icon=IconName::Star class="icon-sm" />
                    " PR Pack"
                </h1>
                <button
                    class="btn btn-outline btn-sm"
                    on:click=move |_| {
                        components::show_toast(&set_toast, "Regenerating…", ToastType::Info);
                        do_reload();
                    }
                    disabled=loading
                >
                    <Icon icon=IconName::Refresh class="icon-sm" />
                    " Regenerate"
                </button>
            </div>

            {move || {
                if loading.get() {
                    view! {
                        <div class="card" style="width:100%;text-align:center;padding:2rem;">
                            <Icon icon=IconName::Hourglass class="icon-lg" />
                            <p class="subtitle">"Generating PR pack…"</p>
                        </div>
                    }.into_any()
                } else if let Some(err) = error.get() {
                    view! {
                        <div class="card" style="width:100%;padding:1.5rem;">
                            <p style="color:var(--danger, #e53e3e);">"Failed to load: "{err}</p>
                            <button class="btn btn-outline btn-sm" style="margin-top:1rem;" on:click=move |_| do_reload()>
                                "Retry"
                            </button>
                        </div>
                    }.into_any()
                } else if let Some(d) = data.get() {
                    view! {
                        <div style="width:100%;">
                            <p class="subtitle" style="margin-bottom:1rem;">
                                "Copy-pasteable marketing copy. Edit the event config to change these — "
                                "generation is deterministic, no AI."
                            </p>
                            <PackField
                                label="Headline"
                                icon=IconName::Star
                                value=d.pack.headline.clone()
                                set_toast=set_toast
                            />
                            <PackField
                                label="Short blurb"
                                icon=IconName::Lightbulb
                                value=d.pack.short_blurb.clone()
                                set_toast=set_toast
                            />
                            <PackField
                                label="Social post (X / Twitter)"
                                icon=IconName::Globe
                                value=d.pack.social_post.clone()
                                set_toast=set_toast
                            />
                            <PackField
                                label="Calendar text"
                                icon=IconName::Calendar
                                value=d.pack.calendar_text.clone()
                                set_toast=set_toast
                            />
                            <PackField
                                label="Email snippet"
                                icon=IconName::Link
                                value=d.pack.email_snippet.clone()
                                set_toast=set_toast
                            />
                            <PackField
                                label="Deposit terms"
                                icon=IconName::Coin
                                value=d.pack.deposit_terms.clone()
                                set_toast=set_toast
                            />
                            <OrganizersCard organizers=d.pack.organizers.clone() set_toast=set_toast />
                        </div>
                    }.into_any()
                } else {
                    view! { <div></div> }.into_any()
                }
            }}
        </div>
    }
}

/// A single copy-to-clipboard card for one PR pack field.
#[component]
fn PackField(
    label: &'static str,
    icon: IconName,
    value: String,
    set_toast: WriteSignal<Option<components::ToastMessage>>,
) -> impl IntoView {
    let label_for_toast = label;
    let value_for_display = value.clone();
    view! {
        <section class="card" style="margin-top:0.75rem;width:100%;">
            <div class="card-header" style="display:flex;justify-content:space-between;align-items:center;">
                <span class="card-title">
                    <Icon icon=icon class="icon-sm" />
                    " " {label}
                </span>
                <button
                    class="btn btn-outline btn-sm"
                    on:click=move |_| {
                        if copy_to_clipboard_js(&value) {
                            components::show_toast(
                                &set_toast,
                                &format!("{label_for_toast} copied"),
                                ToastType::Success,
                            );
                        } else {
                            components::show_toast(
                                &set_toast,
                                "Copy failed — select manually",
                                ToastType::Error,
                            );
                        }
                    }
                >
                    <Icon icon=IconName::Copy class="icon-sm" />
                    " Copy"
                </button>
            </div>
            <div style="white-space:pre-wrap;padding:0.75rem 0;border-top:1px solid var(--border, #e2e8f0);font-size:0.95rem;line-height:1.5;">
                {value_for_display}
            </div>
        </section>
    }
}

/// Organizers card — one copy button per email, since organizers are a list.
#[component]
fn OrganizersCard(
    organizers: Vec<String>,
    set_toast: WriteSignal<Option<components::ToastMessage>>,
) -> impl IntoView {
    view! {
        <section class="card" style="margin-top:0.75rem;width:100%;">
            <div class="card-header">
                <span class="card-title">
                    <Icon icon=IconName::Pin class="icon-sm" />
                    " Organizers"
                </span>
            </div>
            {if organizers.is_empty() {
                view! {
                    <div style="padding:0.75rem 0;border-top:1px solid var(--border, #e2e8f0);">
                        <p class="subtitle" style="margin:0;">"No organizers set."</p>
                    </div>
                }.into_any()
            } else {
                view! {
                    <div style="padding:0.5rem 0;border-top:1px solid var(--border, #e2e8f0);">
                        {organizers.iter().map(|email| {
                            let email_for_click = email.clone();
                            let email_for_display = email.clone();
                            view! {
                                <div style="display:flex;justify-content:space-between;align-items:center;padding:0.25rem 0;">
                                    <span style="font-size:0.95rem;">{email_for_display.clone()}</span>
                                    <button
                                        class="btn btn-outline btn-sm"
                                        on:click=move |_| {
                                            if copy_to_clipboard_js(&email_for_click) {
                                                components::show_toast(
                                                    &set_toast,
                                                    "Email copied",
                                                    ToastType::Success,
                                                );
                                            } else {
                                                components::show_toast(
                                                    &set_toast,
                                                    "Copy failed",
                                                    ToastType::Error,
                                                );
                                            }
                                        }
                                    >
                                        <Icon icon=IconName::Copy class="icon-sm" />
                                    </button>
                                </div>
                            }
                        }).collect::<Vec<_>>()}
                    </div>
                }.into_any()
            }}
        </section>
    }
}
